### ISSUE TITLE
jdbcmapper support 1-n join on constructor injected prop

### ISSUE THREAD

**Issue by arnaudroger** [arnaudroger/SimpleFlatMapper#122]

**Comment by fetchrgs** [comment]
Hi Arnaud,

I tried to use this feature with Tuple2 from the example (https://github.com/arnaudroger/SimpleFlatMapper/wiki/SimpleFlatMapper-JdbcMapper-1-N-relationship) with postgres. As you can see here http://www.postgresql.org/docs/current/static/sql-syntax-lexical.html#SQL-SYNTAX-IDENTIFIERS postgres doesn't permit aliases beginning with numbers. When I changed the numeric prefices in the keys to letters (say, s.id as s_id, p.id as p_id) I get a NullPointerException("propertyGetter is null"); in the MapperFieldMapper. Are the numeric prefices in the example sensitive to the join resolution/property introspection mechanism somehow?

Thanks,
Richard

**Comment by arnaudroger** [comment]
The index matches against the first number elt0 or 0 should work. 
Would you have the full stack trace?

**Comment by arnaudroger** [comment]
Dos no read first can you you try elt0_id instead of the letter?

**Comment by arnaudroger** [comment]
It's using the index to figure out under which part of the tuple to associate the column. If omitted as in id instead of elt0_id it will try to do an index discovery. But then I'm not sure of how you can the associate the key. Something I would need to look at

**Comment by fetchrgs** [comment]
Hi,

The stack trace is here:

Exception in thread "main" org.sfm.map.MapperBuildingException: propertyGetter is null
	at org.sfm.map.impl.AbstractFieldMapperMapperBuilder.getConstructorFieldMappersAndInstantiator(AbstractFieldMapperMapperBuilder.java:93)
	at org.sfm.jdbc.JdbcMapperBuilder.buildMapper(JdbcMapperBuilder.java:99)
	at org.sfm.jdbc.JdbcMapperBuilder.mapper(JdbcMapperBuilder.java:87)
	at org.sfm.jdbc.impl.DynamicJdbcMapper.getMapper(DynamicJdbcMapper.java:135)
	at org.sfm.jdbc.impl.DynamicJdbcMapper.getMapper(DynamicJdbcMapper.java:120)
	at org.sfm.jdbc.impl.DynamicJdbcMapper.stream(DynamicJdbcMapper.java:105)
	at jdbc.dao.ExchangeDao.exchanges(ExchangeDao.java:48)
Caused by: java.lang.NullPointerException: propertyGetter is null
	at org.sfm.map.impl.fieldmapper.MapperFieldMapper.<init>(MapperFieldMapper.java:27)
	at org.sfm.map.impl.AbstractFieldMapperMapperBuilder.newMapperFieldMapper(AbstractFieldMapperMapperBuilder.java:143)
	at org.sfm.map.impl.AbstractFieldMapperMapperBuilder.constructorInjections(AbstractFieldMapperMapperBuilder.java:124)
	at org.sfm.map.impl.AbstractFieldMapperMapperBuilder.getConstructorFieldMappersAndInstantiator(AbstractFieldMapperMapperBuilder.java:88)

I tried element0, elt0 but no joy... Anyway, to do this generically behind the scenes would be a very cool feature.

**Comment by arnaudroger** [comment]
I created to ticket on for the table prefix to element marching and one to have better error message. 
Could you send me the exact query you were using and the object your mapping to? By mail if you want

**Comment by arnaudroger** [comment]
I identify where the problem comes from 
created the ticket https://github.com/arnaudroger/SimpleFlatMapper/issues/140
It happens when asm is not present - it's an optional dependency -. the constructor args don't get resolve with their proper name then and it fails to get the getter.

If you can add asm 5 to your pom then it should work.

		<dependency>
			<groupId>org.ow2.asm</groupId>
			<artifactId>asm</artifactId>
			<version>5.0.3</version>
			<scope>provided</scope>
		</dependency>

I'll try to find a solution so that it does not need it.
