### ISSUE TITLE
can't map raw enum entry

### ISSUE THREAD

**Issue by a8t3r** [arnaudroger/SimpleFlatMapper#123]
```java
public enum Type {
        type1   ("1"), type2   ("2"), type3   ("3"), type4   ("4");

        private String value;
        Type(String ... values) { this.value = values[0]; }
        public String getValue() { return value;  }
    }

JdbcMapperBuilder<Type> builder = new JdbcMapperBuilder<Type>(Type.class);
```
On `builder` construction `ReflectionConstructorDefinitionFactory` (asm is disabled) throws an exception like:

>Caused by: java.lang.ArrayIndexOutOfBoundsException: 1
	at org.sfm.reflect.ReflectionConstructorDefinitionFactory.getConstructorParameters(ReflectionConstructorDefinitionFactory.java:32)
	at org.sfm.reflect.ReflectionConstructorDefinitionFactory.extractConstructors(ReflectionConstructorDefinitionFactory.java:18)
	at org.sfm.reflect.ReflectionService.extractConstructors(ReflectionService.java:115)

It seems you're using `getTypeParameters()` and `getGenericParameterTypes()` which produce unexpected behaviour on enum types

**Comment by arnaudroger** [comment]
thanks will look at that, you are really using that stuff :) do you need that asap?

**Comment by a8t3r** [comment]
thanks, don't rush
