### ISSUE TITLE
Java 8 java.time API (JSR-310) Support

### ISSUE THREAD

**Issue by driverpt** [arnaudroger/SimpleFlatMapper#318]
Support for mapping javax.sql.Timestamp to LocalDateTime for example.

**Comment by arnaudroger** [comment]
I believe it should work, did you get an error?

MyObject {
 LocalDateTime dateTime;
}
should be converted.

there are test in ResultSetGetterFactoryTest. If it does not could describe what problem are you having? which version? which classifier?

Regards.

**Comment by driverpt** [comment]
@arnaudroger, i don't have the stack trace right now, but the Mapping results in a StackoverflowException. It calls the Recursive Internal Mapping to LocalDateTime, but an infinite calls to String mapping after that.
I can only attach the Stacktrace later today, but this is what i managed to "Trace".

**Comment by arnaudroger** [comment]
Thanks for that I'll try to reproduce it.
what is the underlying type of the field in the db?

**Comment by driverpt** [comment]
Postgresql Timestamp

**Comment by arnaudroger** [comment]
I tried to reproduce it on my local postgres and insert and read worked fine. 
I'll need more details to reproduce the issue. if you can email me the code that instantiate the mapper/crud the structure of the object and of the table. And the stacktrace I'll have a look.

**Comment by arnaudroger** [comment]
added https://github.com/arnaudroger/SimpleFlatMapper/blob/8f8f44de2fed91becc16b027c2868f8fac0d98ce/sfm/src/test/java/org/sfm/jdbc/Issue318Test.java to try to reproduce but works fine.

**Comment by driverpt** [comment]
Hello, sorry for the delay on this.

I'll paste the classes "obfuscated":
```
@Data
public class SomeClass {
    private UUID id;
    private String name;
    private List<SomeNestedClass> someCollection;
    private LocalDateTime createdAt;
    private LocalDateTime lastUpdatedAt;
    private boolean isDeleted;
}
```

By putting a breakpoint on ConstantSourceFieldMapperFactoryImpl.java:98, i notice that the infinite recursion begins after the LocalDatetime property is passed. It starts infinite recursion with a String type.

Stacktrace:
```
23:45:21 [http-nio-8080-exec-3] ERROR org.apache.catalina.core.ContainerBase.[Tomcat].[localhost].[/].[some.package.JerseyConfig] - Servlet.service() for servlet [some.package.JerseyConfig] in context with path [] threw exception [org.glassfish.jersey.server.ContainerException: java.lang.StackOverflowError] with root cause
java.lang.StackOverflowError
	at org.sfm.reflect.TypeHelper.areEquals(TypeHelper.java:188) ~[sfm-2.9.6.jar:?]
	at org.sfm.utils.conv.ConverterFactory.getConverter(ConverterFactory.java:165) ~[sfm-2.9.6.jar:?]
	at org.sfm.jooq.RecordGetterFactory.newRecordGetterWithConverter(RecordGetterFactory.java:45) ~[sfm-jooq-2.9.6.jar:?]
	at org.sfm.jooq.RecordGetterFactory.newGetter(RecordGetterFactory.java:40) ~[sfm-jooq-2.9.6.jar:?]
	at org.sfm.jooq.RecordGetterFactory.newGetter(RecordGetterFactory.java:18) ~[sfm-jooq-2.9.6.jar:?]
	at org.sfm.map.impl.fieldmapper.ConstantSourceFieldMapperFactoryImpl.getterFromFactory(ConstantSourceFieldMapperFactoryImpl.java:104) ~[sfm-2.9.6.jar:?]
	at org.sfm.map.impl.fieldmapper.ConstantSourceFieldMapperFactoryImpl.getterFromFactory(ConstantSourceFieldMapperFactoryImpl.java:116) ~[sfm-2.9.6.jar:?]
	at org.sfm.map.impl.fieldmapper.ConstantSourceFieldMapperFactoryImpl.getterFromFactory(ConstantSourceFieldMapperFactoryImpl.java:116) ~[sfm-2.9.6.jar:?]
	at org.sfm.map.impl.fieldmapper.ConstantSourceFieldMapperFactoryImpl.getterFromFactory(ConstantSourceFieldMapperFactoryImpl.java:116) ~[sfm-2.9.6.jar:?]
	at org.sfm.map.impl.fieldmapper.ConstantSourceFieldMapperFactoryImpl.getterFromFactory(ConstantSourceFieldMapperFactoryImpl.java:116) ~[sfm-2.9.6.jar:?]
	at org.sfm.map.impl.fieldmapper.ConstantSourceFieldMapperFactoryImpl.getterFromFactory(ConstantSourceFieldMapperFactoryImpl.java:116) ~[sfm-2.9.6.jar:?]
	at org.sfm.map.impl.fieldmapper.ConstantSourceFieldMapperFactoryImpl.getterFromFactory(ConstantSourceFieldMapperFactoryImpl.java:116) ~[sfm-2.9.6.jar:?]
	at org.sfm.map.impl.fieldmapper.ConstantSourceFieldMapperFactoryImpl.getterFromFactory(ConstantSourceFieldMapperFactoryImpl.java:116) ~[sfm-2.9.6.jar:?]
	at org.sfm.map.impl.fieldmapper.ConstantSourceFieldMapperFactoryImpl.getterFromFactory(ConstantSourceFieldMapperFactoryImpl.java:116) ~[sfm-2.9.6.jar:?]
	at org.sfm.map.impl.fieldmapper.ConstantSourceFieldMapperFactoryImpl.getterFromFactory(ConstantSourceFieldMapperFactoryImpl.java:116) ~[sfm-2.9.6.jar:?]
	at org.sfm.map.impl.fieldmapper.ConstantSourceFieldMapperFactoryImpl.getterFromFactory(ConstantSourceFieldMapperFactoryImpl.java:116) ~[sfm-2.9.6.jar:?]
	at org.sfm.map.impl.fieldmapper.ConstantSourceFieldMapperFactoryImpl.getterFromFactory(ConstantSourceFieldMapperFactoryImpl.java:116) ~[sfm-2.9.6.jar:?]
	at org.sfm.map.impl.fieldmapper.ConstantSourceFieldMapperFactoryImpl.getterFromFactory(ConstantSourceFieldMapperFactoryImpl.java:116) ~[sfm-2.9.6.jar:?]
	at org.sfm.map.impl.fieldmapper.ConstantSourceFieldMapperFactoryImpl.getterFromFactory(ConstantSourceFieldMapperFactoryImpl.java:116) ~[sfm-2.9.6.jar:?]
	at org.sfm.map.impl.fieldmapper.ConstantSourceFieldMapperFactoryImpl.getterFromFactory(ConstantSourceFieldMapperFactoryImpl.java:116) ~[sfm-2.9.6.jar:?]
	at org.sfm.map.impl.fieldmapper.ConstantSourceFieldMapperFactoryImpl.getterFromFactory(ConstantSourceFieldMapperFactoryImpl.java:116) ~[sfm-2.9.6.jar:?]
	at org.sfm.map.impl.fieldmapper.ConstantSourceFieldMapperFactoryImpl.getterFromFactory(ConstantSourceFieldMapperFactoryImpl.java:116) ~[sfm-2.9.6.jar:?]
	at org.sfm.map.impl.fieldmapper.ConstantSourceFieldMapperFactoryImpl.getterFromFactory(ConstantSourceFieldMapperFactoryImpl.java:116) ~[sfm-2.9.6.jar:?]
	at org.sfm.map.impl.fieldmapper.ConstantSourceFieldMapperFactoryImpl.getterFromFactory(ConstantSourceFieldMapperFactoryImpl.java:116) ~[sfm-2.9.6.jar:?]
	at org.sfm.map.impl.fieldmapper.ConstantSourceFieldMapperFactoryImpl.getterFromFactory(ConstantSourceFieldMapperFactoryImpl.java:116) ~[sfm-2.9.6.jar:?]
	at org.sfm.map.impl.fieldmapper.ConstantSourceFieldMapperFactoryImpl.getterFromFactory(ConstantSourceFieldMapperFactoryImpl.java:116) ~[sfm-2.9.6.jar:?]
	at org.sfm.map.impl.fieldmapper.ConstantSourceFieldMapperFactoryImpl.getterFromFactory(ConstantSourceFieldMapperFactoryImpl.java:116) ~[sfm-2.9.6.jar:?]
	at org.sfm.map.impl.fieldmapper.ConstantSourceFieldMapperFactoryImpl.getterFromFactory(ConstantSourceFieldMapperFactoryImpl.java:116) ~[sfm-2.9.6.jar:?]
	at org.sfm.map.impl.fieldmapper.ConstantSourceFieldMapperFactoryImpl.getterFromFactory(ConstantSourceFieldMapperFactoryImpl.java:116) ~[sfm-2.9.6.jar:?]
	at org.sfm.map.impl.fieldmapper.ConstantSourceFieldMapperFactoryImpl.getterFromFactory(ConstantSourceFieldMapperFactoryImpl.java:116) ~[sfm-2.9.6.jar:?]
	at org.sfm.map.impl.fieldmapper.ConstantSourceFieldMapperFactoryImpl.getterFromFactory(ConstantSourceFieldMapperFactoryImpl.java:116) ~[sfm-2.9.6.jar:?]
	at org.sfm.map.impl.fieldmapper.ConstantSourceFieldMapperFactoryImpl.getterFromFactory(ConstantSourceFieldMapperFactoryImpl.java:116) ~[sfm-2.9.6.jar:?]
	at org.sfm.map.impl.fieldmapper.ConstantSourceFieldMapperFactoryImpl.getterFromFactory(ConstantSourceFieldMapperFactoryImpl.java:116) ~[sfm-2.9.6.jar:?]
	at org.sfm.map.impl.fieldmapper.ConstantSourceFieldMapperFactoryImpl.getterFromFactory(ConstantSourceFieldMapperFactoryImpl.java:116) ~[sfm-2.9.6.jar:?]
	at org.sfm.map.impl.fieldmapper.ConstantSourceFieldMapperFactoryImpl.getterFromFactory(ConstantSourceFieldMapperFactoryImpl.java:116) ~[sfm-2.9.6.jar:?]
	at org.sfm.map.impl.fieldmapper.ConstantSourceFieldMapperFactoryImpl.getterFromFactory(ConstantSourceFieldMapperFactoryImpl.java:116) ~[sfm-2.9.6.jar:?]
	at org.sfm.map.impl.fieldmapper.ConstantSourceFieldMapperFactoryImpl.getterFromFactory(ConstantSourceFieldMapperFactoryImpl.java:116) ~[sfm-2.9.6.jar:?]
	at org.sfm.map.impl.fieldmapper.ConstantSourceFieldMapperFactoryImpl.getterFromFactory(ConstantSourceFieldMapperFactoryImpl.java:116) ~[sfm-2.9.6.jar:?]
	at org.sfm.map.impl.fieldmapper.ConstantSourceFieldMapperFactoryImpl.getterFromFactory(ConstantSourceFieldMapperFactoryImpl.java:116) ~[sfm-2.9.6.jar:?]
	at org.sfm.map.impl.fieldmapper.ConstantSourceFieldMapperFactoryImpl.getterFromFactory(ConstantSourceFieldMapperFactoryImpl.java:116) ~[sfm-2.9.6.jar:?]
	at org.sfm.map.impl.fieldmapper.ConstantSourceFieldMapperFactoryImpl.getterFromFactory(ConstantSourceFieldMapperFactoryImpl.java:116) ~[sfm-2.9.6.jar:?]
	at org.sfm.map.impl.fieldmapper.ConstantSourceFieldMapperFactoryImpl.getterFromFactory(ConstantSourceFieldMapperFactoryImpl.java:116) ~[sfm-2.9.6.jar:?]
	at org.sfm.map.impl.fieldmapper.ConstantSourceFieldMapperFactoryImpl.getterFromFactory(ConstantSourceFieldMapperFactoryImpl.java:116) ~[sfm-2.9.6.jar:?]
	at org.sfm.map.impl.fieldmapper.ConstantSourceFieldMapperFactoryImpl.getterFromFactory(ConstantSourceFieldMapperFactoryImpl.java:116) ~[sfm-2.9.6.jar:?]
	at org.sfm.map.impl.fieldmapper.ConstantSourceFieldMapperFactoryImpl.getterFromFactory(ConstantSourceFieldMapperFactoryImpl.java:116) ~[sfm-2.9.6.jar:?]
	at org.sfm.map.impl.fieldmapper.ConstantSourceFieldMapperFactoryImpl.getterFromFactory(ConstantSourceFieldMapperFactoryImpl.java:116) ~[sfm-2.9.6.jar:?]
	at org.sfm.map.impl.fieldmapper.ConstantSourceFieldMapperFactoryImpl.getterFromFactory(ConstantSourceFieldMapperFactoryImpl.java:116) ~[sfm-2.9.6.jar:?]
	at org.sfm.map.impl.fieldmapper.ConstantSourceFieldMapperFactoryImpl.getterFromFactory(ConstantSourceFieldMapperFactoryImpl.java:116) ~[sfm-2.9.6.jar:?]
	at org.sfm.map.impl.fieldmapper.ConstantSourceFieldMapperFactoryImpl.getterFromFactory(ConstantSourceFieldMapperFactoryImpl.java:116) ~[sfm-2.9.6.jar:?]
	at org.sfm.map.impl.fieldmapper.ConstantSourceFieldMapperFactoryImpl.getterFromFactory(ConstantSourceFieldMapperFactoryImpl.java:116) ~[sfm-2.9.6.jar:?]
	at org.sfm.map.impl.fieldmapper.ConstantSourceFieldMapperFactoryImpl.getterFromFactory(ConstantSourceFieldMapperFactoryImpl.java:116) ~[sfm-2.9.6.jar:?]
	at org.sfm.map.impl.fieldmapper.ConstantSourceFieldMapperFactoryImpl.getterFromFactory(ConstantSourceFieldMapperFactoryImpl.java:116) ~[sfm-2.9.6.jar:?]
	at org.sfm.map.impl.fieldmapper.ConstantSourceFieldMapperFactoryImpl.getterFromFactory(ConstantSourceFieldMapperFactoryImpl.java:116) ~[sfm-2.9.6.jar:?]
	at org.sfm.map.impl.fieldmapper.ConstantSourceFieldMapperFactoryImpl.getterFromFactory(ConstantSourceFieldMapperFactoryImpl.java:116) ~[sfm-2.9.6.jar:?]
	at org.sfm.map.impl.fieldmapper.ConstantSourceFieldMapperFactoryImpl.getterFromFactory(ConstantSourceFieldMapperFactoryImpl.java:116) ~[sfm-2.9.6.jar:?]
	at org.sfm.map.impl.fieldmapper.ConstantSourceFieldMapperFactoryImpl.getterFromFactory(ConstantSourceFieldMapperFactoryImpl.java:116) ~[sfm-2.9.6.jar:?]
	at org.sfm.map.impl.fieldmapper.ConstantSourceFieldMapperFactoryImpl.getterFromFactory(ConstantSourceFieldMapperFactoryImpl.java:116) ~[sfm-2.9.6.jar:?]
	at org.sfm.map.impl.fieldmapper.ConstantSourceFieldMapperFactoryImpl.getterFromFactory(ConstantSourceFieldMapperFactoryImpl.java:116) ~[sfm-2.9.6.jar:?]
	at org.sfm.map.impl.fieldmapper.ConstantSourceFieldMapperFactoryImpl.getterFromFactory(ConstantSourceFieldMapperFactoryImpl.java:116) ~[sfm-2.9.6.jar:?]
	at org.sfm.map.impl.fieldmapper.ConstantSourceFieldMapperFactoryImpl.getterFromFactory(ConstantSourceFieldMapperFactoryImpl.java:116) ~[sfm-2.9.6.jar:?]
	at org.sfm.map.impl.fieldmapper.ConstantSourceFieldMapperFactoryImpl.getterFromFactory(ConstantSourceFieldMapperFactoryImpl.java:116) ~[sfm-2.9.6.jar:?]
	at org.sfm.map.impl.fieldmapper.ConstantSourceFieldMapperFactoryImpl.getterFromFactory(ConstantSourceFieldMapperFactoryImpl.java:116) ~[sfm-2.9.6.jar:?]
	at org.sfm.map.impl.fieldmapper.ConstantSourceFieldMapperFactoryImpl.getterFromFactory(ConstantSourceFieldMapperFactoryImpl.java:116) ~[sfm-2.9.6.jar:?]
	at org.sfm.map.impl.fieldmapper.ConstantSourceFieldMapperFactoryImpl.getterFromFactory(ConstantSourceFieldMapperFactoryImpl.java:116) ~[sfm-2.9.6.jar:?]
	at org.sfm.map.impl.fieldmapper.ConstantSourceFieldMapperFactoryImpl.getterFromFactory(ConstantSourceFieldMapperFactoryImpl.java:116) ~[sfm-2.9.6.jar:?]
	at org.sfm.map.impl.fieldmapper.ConstantSourceFieldMapperFactoryImpl.getterFromFactory(ConstantSourceFieldMapperFactoryImpl.java:116) ~[sfm-2.9.6.jar:?]
	at org.sfm.map.impl.fieldmapper.ConstantSourceFieldMapperFactoryImpl.getterFromFactory(ConstantSourceFieldMapperFactoryImpl.java:116) ~[sfm-2.9.6.jar:?]
	at org.sfm.map.impl.fieldmapper.ConstantSourceFieldMapperFactoryImpl.getterFromFactory(ConstantSourceFieldMapperFactoryImpl.java:116) ~[sfm-2.9.6.jar:?]
	at org.sfm.map.impl.fieldmapper.ConstantSourceFieldMapperFactoryImpl.getterFromFactory(ConstantSourceFieldMapperFactoryImpl.java:116) ~[sfm-2.9.6.jar:?]
	at org.sfm.map.impl.fieldmapper.ConstantSourceFieldMapperFactoryImpl.getterFromFactory(ConstantSourceFieldMapperFactoryImpl.java:116) ~[sfm-2.9.6.jar:?]
	at org.sfm.map.impl.fieldmapper.ConstantSourceFieldMapperFactoryImpl.getterFromFactory(ConstantSourceFieldMapperFactoryImpl.java:116) ~[sfm-2.9.6.jar:?]
	at org.sfm.map.impl.fieldmapper.ConstantSourceFieldMapperFactoryImpl.getterFromFactory(ConstantSourceFieldMapperFactoryImpl.java:116) ~[sfm-2.9.6.jar:?]
	at org.sfm.map.impl.fieldmapper.ConstantSourceFieldMapperFactoryImpl.getterFromFactory(ConstantSourceFieldMapperFactoryImpl.java:116) ~[sfm-2.9.6.jar:?]
	at org.sfm.map.impl.fieldmapper.ConstantSourceFieldMapperFactoryImpl.getterFromFactory(ConstantSourceFieldMapperFactoryImpl.java:116) ~[sfm-2.9.6.jar:?]
	at org.sfm.map.impl.fieldmapper.ConstantSourceFieldMapperFactoryImpl.getterFromFactory(ConstantSourceFieldMapperFactoryImpl.java:116) ~[sfm-2.9.6.jar:?]
	at org.sfm.map.impl.fieldmapper.ConstantSourceFieldMapperFactoryImpl.getterFromFactory(ConstantSourceFieldMapperFactoryImpl.java:116) ~[sfm-2.9.6.jar:?]
	at org.sfm.map.impl.fieldmapper.ConstantSourceFieldMapperFactoryImpl.getterFromFactory(ConstantSourceFieldMapperFactoryImpl.java:116) ~[sfm-2.9.6.jar:?]
	at org.sfm.map.impl.fieldmapper.ConstantSourceFieldMapperFactoryImpl.getterFromFactory(ConstantSourceFieldMapperFactoryImpl.java:116) ~[sfm-2.9.6.jar:?]
	at org.sfm.map.impl.fieldmapper.ConstantSourceFieldMapperFactoryImpl.getterFromFactory(ConstantSourceFieldMapperFactoryImpl.java:116) ~[sfm-2.9.6.jar:?]
	at org.sfm.map.impl.fieldmapper.ConstantSourceFieldMapperFactoryImpl.getterFromFactory(ConstantSourceFieldMapperFactoryImpl.java:116) ~[sfm-2.9.6.jar:?]
	at org.sfm.map.impl.fieldmapper.ConstantSourceFieldMapperFactoryImpl.getterFromFactory(ConstantSourceFieldMapperFactoryImpl.java:116) ~[sfm-2.9.6.jar:?]
	at org.sfm.map.impl.fieldmapper.ConstantSourceFieldMapperFactoryImpl.getterFromFactory(ConstantSourceFieldMapperFactoryImpl.java:116) ~[sfm-2.9.6.jar:?]
	at org.sfm.map.impl.fieldmapper.ConstantSourceFieldMapperFactoryImpl.getterFromFactory(ConstantSourceFieldMapperFactoryImpl.java:116) ~[sfm-2.9.6.jar:?]
	at org.sfm.map.impl.fieldmapper.ConstantSourceFieldMapperFactoryImpl.getterFromFactory(ConstantSourceFieldMapperFactoryImpl.java:116) ~[sfm-2.9.6.jar:?]
	at org.sfm.map.impl.fieldmapper.ConstantSourceFieldMapperFactoryImpl.getterFromFactory(ConstantSourceFieldMapperFactoryImpl.java:116) ~[sfm-2.9.6.jar:?]
	at org.sfm.map.impl.fieldmapper.ConstantSourceFieldMapperFactoryImpl.getterFromFactory(ConstantSourceFieldMapperFactoryImpl.java:116) ~[sfm-2.9.6.jar:?]
	at org.sfm.map.impl.fieldmapper.ConstantSourceFieldMapperFactoryImpl.getterFromFactory(ConstantSourceFieldMapperFactoryImpl.java:116) ~[sfm-2.9.6.jar:?]
	at org.sfm.map.impl.fieldmapper.ConstantSourceFieldMapperFactoryImpl.getterFromFactory(ConstantSourceFieldMapperFactoryImpl.java:116) ~[sfm-2.9.6.jar:?]
	at org.sfm.map.impl.fieldmapper.ConstantSourceFieldMapperFactoryImpl.getterFromFactory(ConstantSourceFieldMapperFactoryImpl.java:116) ~[sfm-2.9.6.jar:?]
	at org.sfm.map.impl.fieldmapper.ConstantSourceFieldMapperFactoryImpl.getterFromFactory(ConstantSourceFieldMapperFactoryImpl.java:116) ~[sfm-2.9.6.jar:?]
	at org.sfm.map.impl.fieldmapper.ConstantSourceFieldMapperFactoryImpl.getterFromFactory(ConstantSourceFieldMapperFactoryImpl.java:116) ~[sfm-2.9.6.jar:?]
	at org.sfm.map.impl.fieldmapper.ConstantSourceFieldMapperFactoryImpl.getterFromFactory(ConstantSourceFieldMapperFactoryImpl.java:116) ~[sfm-2.9.6.jar:?]
	at org.sfm.map.impl.fieldmapper.ConstantSourceFieldMapperFactoryImpl.getterFromFactory(ConstantSourceFieldMapperFactoryImpl.java:116) ~[sfm-2.9.6.jar:?]
	at org.sfm.map.impl.fieldmapper.ConstantSourceFieldMapperFactoryImpl.getterFromFactory(ConstantSourceFieldMapperFactoryImpl.java:116) ~[sfm-2.9.6.jar:?]
	at org.sfm.map.impl.fieldmapper.ConstantSourceFieldMapperFactoryImpl.getterFromFactory(ConstantSourceFieldMapperFactoryImpl.java:116) ~[sfm-2.9.6.jar:?]
	at org.sfm.map.impl.fieldmapper.ConstantSourceFieldMapperFactoryImpl.getterFromFactory(ConstantSourceFieldMapperFactoryImpl.java:116) ~[sfm-2.9.6.jar:?]
	at org.sfm.map.impl.fieldmapper.ConstantSourceFieldMapperFactoryImpl.getterFromFactory(ConstantSourceFieldMapperFactoryImpl.java:116) ~[sfm-2.9.6.jar:?]
	at org.sfm.map.impl.fieldmapper.ConstantSourceFieldMapperFactoryImpl.getterFromFactory(ConstantSourceFieldMapperFactoryImpl.java:116) ~[sfm-2.9.6.jar:?]
	at org.sfm.map.impl.fieldmapper.ConstantSourceFieldMapperFactoryImpl.getterFromFactory(ConstantSourceFieldMapperFactoryImpl.java:116) ~[sfm-2.9.6.jar:?]
	at org.sfm.map.impl.fieldmapper.ConstantSourceFieldMapperFactoryImpl.getterFromFactory(ConstantSourceFieldMapperFactoryImpl.java:116) ~[sfm-2.9.6.jar:?]
	at org.sfm.map.impl.fieldmapper.ConstantSourceFieldMapperFactoryImpl.getterFromFactory(ConstantSourceFieldMapperFactoryImpl.java:116) ~[sfm-2.9.6.jar:?]
	at org.sfm.map.impl.fieldmapper.ConstantSourceFieldMapperFactoryImpl.getterFromFactory(ConstantSourceFieldMapperFactoryImpl.java:116) ~[sfm-2.9.6.jar:?]
	at org.sfm.map.impl.fieldmapper.ConstantSourceFieldMapperFactoryImpl.getterFromFactory(ConstantSourceFieldMapperFactoryImpl.java:116) ~[sfm-2.9.6.jar:?]
	at org.sfm.map.impl.fieldmapper.ConstantSourceFieldMapperFactoryImpl.getterFromFactory(ConstantSourceFieldMapperFactoryImpl.java:116) ~[sfm-2.9.6.jar:?]
	at org.sfm.map.impl.fieldmapper.ConstantSourceFieldMapperFactoryImpl.getterFromFactory(ConstantSourceFieldMapperFactoryImpl.java:116) ~[sfm-2.9.6.jar:?]
	at org.sfm.map.impl.fieldmapper.ConstantSourceFieldMapperFactoryImpl.getterFromFactory(ConstantSourceFieldMapperFactoryImpl.java:116) ~[sfm-2.9.6.jar:?]
	at org.sfm.map.impl.fieldmapper.ConstantSourceFieldMapperFactoryImpl.getterFromFactory(ConstantSourceFieldMapperFactoryImpl.java:116) ~[sfm-2.9.6.jar:?]
	at org.sfm.map.impl.fieldmapper.ConstantSourceFieldMapperFactoryImpl.getterFromFactory(ConstantSourceFieldMapperFactoryImpl.java:116) ~[sfm-2.9.6.jar:?]
	at org.sfm.map.impl.fieldmapper.ConstantSourceFieldMapperFactoryImpl.getterFromFactory(ConstantSourceFieldMapperFactoryImpl.java:116) ~[sfm-2.9.6.jar:?]
	at org.sfm.map.impl.fieldmapper.ConstantSourceFieldMapperFactoryImpl.getterFromFactory(ConstantSourceFieldMapperFactoryImpl.java:116) ~[sfm-2.9.6.jar:?]
	at org.sfm.map.impl.fieldmapper.ConstantSourceFieldMapperFactoryImpl.getterFromFactory(ConstantSourceFieldMapperFactoryImpl.java:116) ~[sfm-2.9.6.jar:?]
	at org.sfm.map.impl.fieldmapper.ConstantSourceFieldMapperFactoryImpl.getterFromFactory(ConstantSourceFieldMapperFactoryImpl.java:116) ~[sfm-2.9.6.jar:?]
	at org.sfm.map.impl.fieldmapper.ConstantSourceFieldMapperFactoryImpl.getterFromFactory(ConstantSourceFieldMapperFactoryImpl.java:116) ~[sfm-2.9.6.jar:?]
	at org.sfm.map.impl.fieldmapper.ConstantSourceFieldMapperFactoryImpl.getterFromFactory(ConstantSourceFieldMapperFactoryImpl.java:116) ~[sfm-2.9.6.jar:?]
	at org.sfm.map.impl.fieldmapper.ConstantSourceFieldMapperFactoryImpl.getterFromFactory(ConstantSourceFieldMapperFactoryImpl.java:116) ~[sfm-2.9.6.jar:?]
	at org.sfm.map.impl.fieldmapper.ConstantSourceFieldMapperFactoryImpl.getterFromFactory(ConstantSourceFieldMapperFactoryImpl.java:116) ~[sfm-2.9.6.jar:?]
	at org.sfm.map.impl.fieldmapper.ConstantSourceFieldMapperFactoryImpl.getterFromFactory(ConstantSourceFieldMapperFactoryImpl.java:116) ~[sfm-2.9.6.jar:?]
	at org.sfm.map.impl.fieldmapper.ConstantSourceFieldMapperFactoryImpl.getterFromFactory(ConstantSourceFieldMapperFactoryImpl.java:116) ~[sfm-2.9.6.jar:?]
	at org.sfm.map.impl.fieldmapper.ConstantSourceFieldMapperFactoryImpl.getterFromFactory(ConstantSourceFieldMapperFactoryImpl.java:116) ~[sfm-2.9.6.jar:?]
	at org.sfm.map.impl.fieldmapper.ConstantSourceFieldMapperFactoryImpl.getterFromFactory(ConstantSourceFieldMapperFactoryImpl.java:116) ~[sfm-2.9.6.jar:?]
	at 

...........
```

**Comment by arnaudroger** [comment]
Thanks did not realised it was the jooq integration will fix that asap, should be able to release fix by tomorrow

**Comment by arnaudroger** [comment]
should be fix in version 2.9.7 just pushed to maven central

**Comment by arnaudroger** [comment]
@driverpt have you had any chance to try the last version out?

**Comment by driverpt** [comment]
@arnaudroger , sorry. Totally forgot to give feedback.

It's working, you may consider this issue closed 👍
