### ISSUE TITLE
Jooq 3.8.x support

### ISSUE THREAD

**Issue by rbanikaz** [arnaudroger/SimpleFlatMapper#337]
We are seeing the following exception when upgrading jooq to version 3.8.4 

It seems the type was changed to a field array

Any help would be appreciated
 
```
Caused by: java.lang.UnsupportedOperationException: Cannot extract class from type org.jooq.Field<?>[]
	at org.sfm.reflect.TypeHelper.toClass(TypeHelper.java:22)
	at org.sfm.reflect.TypeHelper.toBoxedClass(TypeHelper.java:176)
	at org.sfm.reflect.TypeHelper.isAssignable(TypeHelper.java:158)
	at org.sfm.reflect.GetterHelper.isCompatible(GetterHelper.java:61)
	at org.sfm.reflect.meta.ObjectClassMeta$2.register(ObjectClassMeta.java:167)
	at org.sfm.reflect.meta.ObjectClassMeta$2.method(ObjectClassMeta.java:127)
	at org.sfm.reflect.meta.ClassVisitor.visit(ClassVisitor.java:19)
	at org.sfm.reflect.meta.ObjectClassMeta.listProperties(ObjectClassMeta.java:119)
	at org.sfm.reflect.meta.ObjectClassMeta.<init>(ObjectClassMeta.java:39)
	at org.sfm.reflect.meta.ObjectClassMeta.<init>(ObjectClassMeta.java:25)
	at org.sfm.reflect.ReflectionService.newClassMeta(ReflectionService.java:102)
	at org.sfm.reflect.ReflectionService.getClassMeta(ReflectionService.java:73)
	at org.sfm.map.mapper.AbstractMapperFactory.getClassMeta(AbstractMapperFactory.java:301)
	at org.sfm.jdbc.JdbcMapperFactory.newMapper(JdbcMapperFactory.java:242)
	at org.sfm.jdbc.JdbcMapperFactory.newMapper(JdbcMapperFactory.java:210)
	
	... 31 more
```

**Comment by arnaudroger** [comment]
Thanks for the report will have a look asap

**Comment by arnaudroger** [comment]
could you send me the class you are trying to map to ?

**Comment by rbanikaz** [comment]
Sure, its an auto-generated class from Jooq 3.8.4: 

```
/**
 * This class is generated by jOOQ
 */
package com.quanticmind.common.model.autogen.mysql.main.tables.records;


import com.quanticmind.common.model.autogen.mysql.main.tables.GlobalMap;
import org.jooq.Field;
import org.jooq.Record1;
import org.jooq.Record2;
import org.jooq.Row2;
import org.jooq.impl.UpdatableRecordImpl;

import javax.annotation.Generated;


/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.8.4"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class GlobalMapRecord extends UpdatableRecordImpl<GlobalMapRecord> implements Record2<String, String> {

    private static final long serialVersionUID = 857041357;

    /**
     * Setter for <code>ivdb_2.global_map.map_key</code>.
     */
    public void setMapKey(String value) {
        set(0, value);
    }

    /**
     * Getter for <code>ivdb_2.global_map.map_key</code>.
     */
    public String getMapKey() {
        return (String) get(0);
    }

    /**
     * Setter for <code>ivdb_2.global_map.value</code>.
     */
    public void setValue(String value) {
        set(1, value);
    }

    /**
     * Getter for <code>ivdb_2.global_map.value</code>.
     */
    public String getValue() {
        return (String) get(1);
    }

    // -------------------------------------------------------------------------
    // Primary key information
    // -------------------------------------------------------------------------

    /**
     * {@inheritDoc}
     */
    @Override
    public Record1<String> key() {
        return (Record1) super.key();
    }

    // -------------------------------------------------------------------------
    // Record2 type implementation
    // -------------------------------------------------------------------------

    /**
     * {@inheritDoc}
     */
    @Override
    public Row2<String, String> fieldsRow() {
        return (Row2) super.fieldsRow();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Row2<String, String> valuesRow() {
        return (Row2) super.valuesRow();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<String> field1() {
        return GlobalMap.GLOBAL_MAP.MAP_KEY;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<String> field2() {
        return GlobalMap.GLOBAL_MAP.VALUE;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String value1() {
        return getMapKey();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String value2() {
        return getValue();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public GlobalMapRecord value1(String value) {
        setMapKey(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public GlobalMapRecord value2(String value) {
        setValue(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public GlobalMapRecord values(String value1, String value2) {
        value1(value1);
        value2(value2);
        return this;
    }

    // -------------------------------------------------------------------------
    // Constructors
    // -------------------------------------------------------------------------

    /**
     * Create a detached GlobalMapRecord
     */
    public GlobalMapRecord() {
        super(GlobalMap.GLOBAL_MAP);
    }

    /**
     * Create a detached, initialised GlobalMapRecord
     */
    public GlobalMapRecord(String mapKey, String value) {
        super(GlobalMap.GLOBAL_MAP);

        set(0, mapKey);
        set(1, value);
    }
}

```

**Comment by arnaudroger** [comment]
hey just curious why are you using a record mapper to map to a jooq record? would jooq not return a GlobalMapRecord if you do a select on the GLOBAL_MAP table?

**Comment by arnaudroger** [comment]
Just pushed 2.14.1 with a fix for that could you check it out, should be available in about 30 minute from now

**Comment by rbanikaz** [comment]
Yes that works thank you!  To answer your question we have a custom framework for handling of JDBC connections in there we have a wrapper method where we take the SQL from jooq use our JDBC then use SFM to map back to jooq.
