### ISSUE TITLE
Asm Issue with Map

### ISSUE THREAD

**Issue by yoelb** [arnaudroger/SimpleFlatMapper#472]
I try to create a ResultSetExtractorImpl from this pojo (using spring-sfm):

```
 public class MyPojo {

        private final String id;
        private final Map<String, String> map;

        public MyPojo(String id, Map<String, String> map) {
            this.id = id;
            this.map = map;
        }
        public Map<String, String> getMap() {
            return map;
        }
        public String getId() {
            return id;
        }
    }
```
When runing :

```
ResultSetExtractorImpl<MyPojo> rsExtractor = JdbcTemplateMapperFactory
                .newInstance()
                .addKeys("id")
                .newResultSetExtractor(MyPojo.class);
```

I get the following error:

```
java.lang.Error: Unexpected error java.lang.ClassNotFoundException: >

	at org.simpleflatmapper.reflect.asm.AsmInstantiatorDefinitionFactory$1$1.createParameter(AsmInstantiatorDefinitionFactory.java:158)
	at org.simpleflatmapper.reflect.asm.AsmInstantiatorDefinitionFactory$1$1.visitEnd(AsmInstantiatorDefinitionFactory.java:120)
	at org.simpleflatmapper.ow2asm.ClassReader.readMethod(ClassReader.java:1021)
	at org.simpleflatmapper.ow2asm.ClassReader.accept(ClassReader.java:693)
	at org.simpleflatmapper.ow2asm.ClassReader.accept(ClassReader.java:506)
	at org.simpleflatmapper.reflect.asm.AsmInstantiatorDefinitionFactory.extractDefinitions(AsmInstantiatorDefinitionFactory.java:41)
	at org.simpleflatmapper.reflect.ReflectionService.extractInstantiator(ReflectionService.java:194)
	at org.simpleflatmapper.reflect.meta.ObjectClassMeta.<init>(ObjectClassMeta.java:39)
	at org.simpleflatmapper.reflect.meta.ObjectClassMeta.<init>(ObjectClassMeta.java:32)
	at org.simpleflatmapper.reflect.ReflectionService.newClassMeta(ReflectionService.java:154)
	at org.simpleflatmapper.reflect.ReflectionService.getClassMeta(ReflectionService.java:128)
	at org.simpleflatmapper.map.mapper.AbstractMapperFactory.getClassMeta(AbstractMapperFactory.java:303)
	at org.simpleflatmapper.jdbc.JdbcMapperFactory.newMapper(JdbcMapperFactory.java:247)
	at org.simpleflatmapper.jdbc.spring.JdbcTemplateMapperFactory.newJdbcMapper(JdbcTemplateMapperFactory.java:49)
	at org.simpleflatmapper.jdbc.spring.JdbcTemplateMapperFactory.newResultSetExtractor(JdbcTemplateMapperFactory.java:74)
	at org.simpleflatmapper.jdbc.spring.JdbcTemplateMapperFactory.newResultSetExtractor(JdbcTemplateMapperFactory.java:69)
```

BTW, there is a documentation of what is generated with ASM?

Thanks

**Comment by arnaudroger** [comment]
Which java version? It generates bytecode instead of using reflection. I’ll have a look ASAP in the mean time you can disable Asm I believe there is a disableasm on the mapper factory.

**Comment by arnaudroger** [comment]
Got it reproduce so should be able to fix relatively quickly thanks for thhebreport

**Comment by arnaudroger** [comment]
The problem is localise to parsing the signature in constructor for more than one type

**Comment by arnaudroger** [comment]
I fixed the issue, though I'm not sure that the Map<String, String> will behave the way you want it to. Map is not supported for joins and just map the column key here map_{key} to the value in the resultset.

the fix should be in maven central in the next hour

**Comment by yoelb** [comment]
Thanks for the fix Arnaud ;)

Your're right, my use case is to map a table of preoperties [col_1: key, col_2: value] relate to my POJO. Its the reason why I would like to use a map (until now my workaround was to use a List of my own inner bean but it's cumbersome). 

Is there a way to do this?
With the use of #addMapping method?
Unfortunatly, `JdbcTeplateMapperFactory` doesn't have `addCustomFieldMapper` method.

Thanks

**Comment by arnaudroger** [comment]
Unfortunately right now the list of key vale is the work around. I ve been meaning to implement that for a bit but never come around to it. Will try to had it

**Comment by arnaudroger** [comment]
@yoelb just pushed on master a first go at supporting entry mapping for Map https://github.com/arnaudroger/SimpleFlatMapper/issues/424
it expect columns to be map_key and map_value.
 I should be able to do a build release later this week with https://github.com/arnaudroger/SimpleFlatMapper/milestone/133
I need to add some test for joins but in theory it should already work.

**Comment by yoelb** [comment]
Hi Arnaud.

Awesome! I try it very soon (hopping today);)
Thanks

2017-11-27 1:15 GMT+02:00 Arnaud Roger <notifications@github.com>:

**Comment by arnaudroger** [comment]
I just need to find a way to make sure it does not generate the different mapping for previous column name so in the final release it will prob need some config somewhere to enable that.

**Comment by yoelb** [comment]
Hi Arnaud, 

thanks a lot for your support and sorry for the late,

I just tested it, the map is created but I have only one element inside the map and it should more entries.
```
SELECT id, name, key as propperties_key, value as properties_value
WHERE table_1 join table_2 on (id)
```
```
ResultSetExtractorImpl<MyBean> rsExtractor = JdbcTemplateMapperFactory
                .newInstance()
                .addKeys(id")
                .newResultSetExtractor(MyBean.class);

public class MyBean {
    private final String id;
    private final Map<String, String> properties; 
    
     public MyBean(String id, Map<String,String> properties) {
       // TODO  
  }
}

```

Thanks

Yoel

**Comment by arnaudroger** [comment]
so by default, the key value mode is not activating to avoid breaking code already out there - code that would have a map_key column where "key" would be the key value.

http://simpleflatmapper.org/0201-property-mapping.html#key-value

you will need to add the MapTypeProperty.KEY_VALUE on the prop from the map as follows 

```
ResultSetExtractorImpl<MyBean> rsExtractor = JdbcTemplateMapperFactory
                .newInstance()
                .addKeys("id")
                .addColumnProperty(col -> col.getName().startsWith("propperties_"), MapTypeProperty.KEY_VALUE)
                .newResultSetExtractor(MyBean.class);
```

can you confirm if it works? If not I'll try and reproduce it locally.
