### ISSUE TITLE
ignorePropertyNotFound not working for JdbcTemplateMapperFactory

### ISSUE THREAD

**Issue by rshan2** [arnaudroger/SimpleFlatMapper#483]
Template and SQL defined as follows:

```java
public Product getProductByCode(final String code) {
	    
    ResultSetExtractor<List<Product>> resultSetExtractor = JdbcTemplateMapperFactory
	                                                                .newInstance()
	                                                                .ignorePropertyNotFound()
	                                                                .addKeys("PRODUCT_ID", "PRODUCT_TYPE_ID")
	                                                                .newResultSetExtractor(ProductModel.class);
	    
    List<Product> products = getJdbcTemplate().query("select p.*, p.PRODUCT_ID as PK, 
p.PRODUCT_TITLE as TITLE, pt.PRODUCT_TYPE_ID as PRODUCT_TYPE_PK, pt.PRODUCT_TYPE as PRODUCT_TYPE_NAME, pt.DESCRIPTION as PRODUCT_TYPE_DESCRIPTION from PRODUCT p left outer join PRODUCT_TYPE pt on pt.PRODUCT_TYPE_ID = p.PRODUCT_TYPE_ID where p.CODE = ? order by p.PRODUCT_ID", 
	            new Object[] {code}, 
	            resultSetExtractor);
	    
    return products.get(0);
}

```
Product.java:

```java
public class Product {
    private Long pk;
    @Deprecated
    private String legacyId;
    private String subTitle;
    private String category;
    private String url;
    private String code;
    private String copyrightYear;
    private String offerCode;
    private ProductType productType;
    private String title;
    private Date publishDate;
    private double productBasePrice;
    private String language;
    private String author;

//getters and setters omitted
```

ProductType.java:

```java
public class ProductType {
    private Long pk;
    private String name;
    private String description;

//getters and setters omitted
}
```

Stack trace:

```
org.simpleflatmapper.map.MapperBuildingException: Could not find eligible property for 'LEGACY_PRODUCT_ID' on  class org.xxxx.xxxxx.model.Product not found  See https://github.com/arnaudroger/SimpleFlatMapper/wiki/Errors_PROPERTY_NOT_FOUND
	at org.simpleflatmapper.map.error.RethrowMapperBuilderErrorHandler.propertyNotFound(RethrowMapperBuilderErrorHandler.java:26)
	at org.simpleflatmapper.map.mapper.PropertyMappingsBuilder$1.accept(PropertyMappingsBuilder.java:65)
	at org.simpleflatmapper.map.mapper.PropertyMappingsBuilder$1.accept(PropertyMappingsBuilder.java:62)
	at org.simpleflatmapper.map.mapper.PropertyMappingsBuilder._addProperty(PropertyMappingsBuilder.java:99)
	at org.simpleflatmapper.map.mapper.PropertyMappingsBuilder.addProperty(PropertyMappingsBuilder.java:73)
	at org.simpleflatmapper.map.mapper.ConstantSourceMapperBuilder.addMapping(ConstantSourceMapperBuilder.java:109)
	at org.simpleflatmapper.map.mapper.AbstractMapperBuilder.addMapping(AbstractMapperBuilder.java:171)
	at org.simpleflatmapper.jdbc.JdbcMapperFactory$SetRowMapperFactory.newInstance(JdbcMapperFactory.java:310)
	at org.simpleflatmapper.jdbc.JdbcMapperFactory$SetRowMapperFactory.newInstance(JdbcMapperFactory.java:298)
	at org.simpleflatmapper.map.mapper.DynamicSetRowMapper.getMapper(DynamicSetRowMapper.java:101)
	at org.simpleflatmapper.map.mapper.DynamicSetRowMapper.getMapperFromRow(DynamicSetRowMapper.java:95)
	at org.simpleflatmapper.map.mapper.DynamicSetRowMapper.map(DynamicSetRowMapper.java:44)
	at org.simpleflatmapper.jdbc.JdbcMapperFactory$DynamicJdbcSetRowMapper.map(JdbcMapperFactory.java:251)
	at org.simpleflatmapper.jdbc.spring.RowMapperImpl.mapRow(RowMapperImpl.java:55)
	at org.springframework.jdbc.core.RowMapperResultSetExtractor.extractData(RowMapperResultSetExtractor.java:93)
	at org.springframework.jdbc.core.RowMapperResultSetExtractor.extractData(RowMapperResultSetExtractor.java:60)
	at org.springframework.jdbc.core.JdbcTemplate$1.doInPreparedStatement(JdbcTemplate.java:697)
	at org.springframework.jdbc.core.JdbcTemplate.execute(JdbcTemplate.java:633)
	at org.springframework.jdbc.core.JdbcTemplate.query(JdbcTemplate.java:684)
	at org.springframework.jdbc.core.JdbcTemplate.query(JdbcTemplate.java:716)
	at org.springframework.jdbc.core.JdbcTemplate.query(JdbcTemplate.java:726)
	at org.springframework.jdbc.core.JdbcTemplate.query(JdbcTemplate.java:776)

```

Product DDL:

```
CREATE TABLE PRODUCT
(
  PRODUCT_ID             NUMBER(30) NOT NULL
    CONSTRAINT XPKPRODUCT
    PRIMARY KEY,
  LEGACY_PRODUCT_ID    VARCHAR2(30),
  PUBLISHER_ID           NUMBER(30)
    CONSTRAINT R_30
    REFERENCES PUBLISHER
    ON DELETE CASCADE,
  PRODUCT_TITLE          VARCHAR2(520),
  PRODUCT_TYPE_ID        NUMBER(30)
    CONSTRAINT R_9
    REFERENCES PRODUCT_TYPE
    ON DELETE CASCADE,
  PRODUCT_CATEGORY       VARCHAR2(1),
  AUTHOR                 VARCHAR2(200),
  URL                    VARCHAR2(100),
  STATUS                 VARCHAR2(20)  DEFAULT 'active'
    CONSTRAINT PRODSTATUS_VALIDATION
    CHECK (status IN ('active', 'inactive')),
  UPDATED_BY             VARCHAR2(20),
  UPDATED_DATE           TIMESTAMP(6)  DEFAULT SYSDATE,
  CREATED_BY             VARCHAR2(20),
  CREATED_DATE           TIMESTAMP(6)  DEFAULT SYSDATE,
  IMPRINT_ID             NUMBER
    CONSTRAINT PRODUCT_IMPRINT_FK1
    REFERENCES IMPRINT
    ON DELETE CASCADE,
  STATUS_REASON          NUMBER,
  PUBLISH_DATE           DATE          DEFAULT NULL,
  CODE                VARCHAR2(20)  DEFAULT NULL,
  COPYRIGHT_YEAR         NUMBER        DEFAULT NULL,
  OFFER_CODE             VARCHAR2(255) DEFAULT NULL,
  EISXN                  VARCHAR2(20)  DEFAULT NULL,
  LANGUAGE               VARCHAR2(50)  DEFAULT NULL,
  LIVE_DATE              DATE          DEFAULT NULL,
  LIVE_STATUS            VARCHAR2(10)  DEFAULT NULL
    CONSTRAINT PRODLIVE_STATUS
    CHECK (LIVE_STATUS IN ('true', 'false')),
  DEWEY_DECIMAL          VARCHAR2(100) DEFAULT NULL
)
```

Note that the column LEGACY_PRODUCT_ID does not align with the Java POJO Product.legacyId, however, I don't need it and was hoping to simply skip all deprecated fields with ignorePropertyNotFound rather than explicitly define aliases in the SQL for those that don't match the POJO.

If I replace "select p.*" with explicit column names and aliases it works fine.

Thanks in advance for your assistance and great job with SFM.

**Comment by arnaudroger** [comment]
Thanks for the big report. I’ll have a look.

**Comment by arnaudroger** [comment]
Meant bug... autocorrect ...

**Comment by arnaudroger** [comment]
just pushed 3.15.4 with a fix to maven central should be available in the next 10-30 mn.

**Comment by rshan2** [comment]
Works perfectly. Thanks for the prompt response!
