### ISSUE TITLE
IllegalArgumentException: null when upgrading to JRE10

### ISSUE THREAD

**Issue by anuraaga** [arnaudroger/SimpleFlatMapper#507]
Some code that uses sfm-jooq to fetch into a JOOQ generated POJO worked fine with JRE9 but when upgrading to JRE10, it shows the below exception. Let me know if there is more information that can help - the POJO just has a few JOOQ `ULong`, `LocalDateTime`, and an enum.

```
java.lang.IllegalArgumentException: null at org.simpleflatmapper.ow2asm.ClassReader.<init>(ClassReader.java:439) ~[sfm-reflect-3.17.1-jdk9.jar:?] at org.simpleflatmapper.ow2asm.ClassReader.<init>(ClassReader.java:423) ~[sfm-reflect-3.17.1-jdk9.jar:?] at org.simpleflatmapper.ow2asm.ClassReader.<init>(ClassReader.java:509) ~[sfm-reflect-3.17.1-jdk9.jar:?] at org.simpleflatmapper.reflect.asm.AsmInstantiatorDefinitionFactory.extractDefinitions(AsmInstantiatorDefinitionFactory.java:40) ~[sfm-reflect-3.17.1-jdk9.jar:?] at org.simpleflatmapper.reflect.ReflectionService.extractInstantiator(ReflectionService.java:200) ~[sfm-reflect-3.17.1-jdk9.jar:?] at org.simpleflatmapper.reflect.meta.ObjectClassMeta.<init>(ObjectClassMeta.java:39) ~[sfm-reflect-3.17.1-jdk9.jar:?] at org.simpleflatmapper.reflect.meta.ObjectClassMeta.<init>(ObjectClassMeta.java:32) ~[sfm-reflect-3.17.1-jdk9.jar:?] at org.simpleflatmapper.reflect.ReflectionService.newClassMeta(ReflectionService.java:160) ~[sfm-reflect-3.17.1-jdk9.jar:?] at org.simpleflatmapper.reflect.ReflectionService.getClassMeta(ReflectionService.java:128) ~[sfm-reflect-3.17.1-jdk9.jar:?] at org.simpleflatmapper.reflect.meta.PropertyMeta.newPropertyClassMeta(PropertyMeta.java:53) ~[sfm-reflect-3.17.1-jdk9.jar:?] at org.simpleflatmapper.reflect.meta.PropertyMeta.getPropertyClassMeta(PropertyMeta.java:46) ~[sfm-reflect-3.17.1-jdk9.jar:?] at org.simpleflatmapper.reflect.meta.ObjectPropertyFinder.lookForSubProperty(ObjectPropertyFinder.java:113) ~[sfm-reflect-3.17.1-jdk9.jar:?] at org.simpleflatmapper.reflect.meta.ObjectPropertyFinder.lookForConstructor(ObjectPropertyFinder.java:66) ~[sfm-reflect-3.17.1-jdk9.jar:?] at org.simpleflatmapper.reflect.meta.ObjectPropertyFinder.lookForProperties(ObjectPropertyFinder.java:38) ~[sfm-reflect-3.17.1-jdk9.jar:?] at org.simpleflatmapper.reflect.meta.PropertyFinder.findProperty(PropertyFinder.java:28) ~[sfm-reflect-3.17.1-jdk9.jar:?] at org.simpleflatmapper.map.mapper.PropertyMappingsBuilder._addProperty(PropertyMappingsBuilder.java:95) ~[sfm-map-3.17.1-jdk9.jar:?] at org.simpleflatmapper.map.mapper.PropertyMappingsBuilder.addProperty(PropertyMappingsBuilder.java:73) ~[sfm-map-3.17.1-jdk9.jar:?] at org.simpleflatmapper.map.mapper.ConstantSourceMapperBuilder.addMapping(ConstantSourceMapperBuilder.java:109) ~[sfm-map-3.17.1-jdk9.jar:?] at org.simpleflatmapper.jooq.JooqMapperBuilder.addField(JooqMapperBuilder.java:62) ~[sfm-jooq-3.17.1-jdk9.jar:?] at org.simpleflatmapper.jooq.SfmRecordMapperProvider.buildMapper(SfmRecordMapperProvider.java:57) ~[sfm-jooq-3.17.1-jdk9.jar:?] at org.simpleflatmapper.jooq.SfmRecordMapperProvider.provide(SfmRecordMapperProvider.java:41) ~[sfm-jooq-3.17.1-jdk9.jar:?] at org.jooq.impl.AbstractRecord.into(AbstractRecord.java:691) ~[jooq-3.10.6.jar:?] at org.jooq.impl.AbstractResultQuery.fetchOneInto(AbstractResultQuery.java:556) ~[jooq-3.10.6.jar:?] at org.jooq.impl.SelectImpl.fetchOneInto(SelectImpl.java:2790) ~[jooq-3.10.6.jar:?] at 
```

**Comment by arnaudroger** [comment]
thanks for the bug report will check that out.

**Comment by arnaudroger** [comment]
I’ll do a release with the fix version ASAP the jar has been package with an up to Java 9 asm

**Comment by arnaudroger** [comment]
just pushed 3.17.2 to maven central, my build machine had the wrong version of the repackage asm. it should be fixed now. could you try it out when you can?

**Comment by anuraaga** [comment]
Thanks for the quick fix - it's working fine now.
