### ISSUE TITLE
CSV parsing and @Column property mapping

### ISSUE THREAD

**Issue by sikoried** [arnaudroger/SimpleFlatMapper#516]
Im trying to parse lines from a CSV into a stream of Objects:

```
V_ID;Name;Liga;
1;FC Bayern München;1;
2;FC Schalke 04;1;
3;Borussia Dortmund;1;
4;RB Leipzig;1;
```

```java
public class Verein {
	@Column(name="V_ID")
	private int id;

	@Column(name="Name")
	private String name;

	@Column(name="Liga")
	private int liga;
}
```
```java
Reader reader = ...; // Reader works
Map<Integer, Verein> vereine = CsvParser
		.separator(';')
		.mapTo(Verein.class)
		.stream(reader)
		.collect(Collectors.toMap(Verein::getId, Function.identity()));
```

I'm getting the following exception:
```
org.simpleflatmapper.map.MapperBuildingException: Could not find eligible property for 'Name' on  class ch10.Verein not found  See https://github.com/arnaudroger/SimpleFlatMapper/wiki/Errors_PROPERTY_NOT_FOUND

	at org.simpleflatmapper.map.error.RethrowMapperBuilderErrorHandler.propertyNotFound(RethrowMapperBuilderErrorHandler.java:26)
	at org.simpleflatmapper.map.mapper.PropertyMappingsBuilder$1.accept(PropertyMappingsBuilder.java:66)
	at org.simpleflatmapper.map.mapper.PropertyMappingsBuilder$1.accept(PropertyMappingsBuilder.java:63)
	at org.simpleflatmapper.map.mapper.PropertyMappingsBuilder._addProperty(PropertyMappingsBuilder.java:100)
	at org.simpleflatmapper.map.mapper.PropertyMappingsBuilder.addProperty(PropertyMappingsBuilder.java:74)
	at org.simpleflatmapper.csv.CsvMapperBuilder.addMapping(CsvMapperBuilder.java:119)
	at org.simpleflatmapper.csv.impl.DynamicCsvMapper.buildMapper(DynamicCsvMapper.java:144)
	at org.simpleflatmapper.csv.impl.DynamicCsvMapper.getCsvMapper(DynamicCsvMapper.java:134)
	at org.simpleflatmapper.csv.impl.DynamicCsvMapper.getDelegateMapper(DynamicCsvMapper.java:107)
	at org.simpleflatmapper.csv.impl.DynamicCsvMapper.stream(DynamicCsvMapper.java:120)
	at org.simpleflatmapper.csv.CsvParser$MapWithDSL.stream(CsvParser.java:1103)
	at ch10.Bundesliga.loadFromResource(Bundesliga.java:44)
	at ch10.BundesligaTest.loadFromResource(BundesligaTest.java:13)
	...
```

It does work, if I manually parse the lines; it does not work either, if I set up the mappings manually. Am I missing something obvious like a configuration step? Thanks!

**Comment by arnaudroger** [comment]
Will trying it out thanks for the bug report

**Comment by arnaudroger** [comment]
Just quickly looking at it do you have a constructor at setters? Sfm respects encapsulation so won’t try to inject private field directly

**Comment by sikoried** [comment]
Ah got it... I changed the class to include a constructor

```java
public Verein(int V_ID, String name, int liga) {
	this.id = V_ID;
	this.name = name;
	this.liga = liga;
}
```
and modified the CSV file to get rid of the trailing `;` in each line, now it works!
So I guess the parser inspects the constructor(s) and then tries to map column fields to arguments? Must have missed that in the docs...

Regarding the `@Column(name=...)` annotations: in what way are those used at all? The JPA ones can't be attached to method arguments. If I were to contribute, where would it make most sense to add the inspection code that reflects on the `@Column` annotations and adds mappings? (and sets values via reflection?)

**Comment by arnaudroger** [comment]
If your field name match the name  in the header then there is no need for annotation. If I can remember properly those annotation or manage through an alias provider interface I’ll check tomorrow.

**Comment by arnaudroger** [comment]
you look at the JpaAliasProvider, it would need a new annotation defined too that prob would belong to a separate package as it can work with all the mapping strategy. though I'm generally quite skeptical of annotation, the way you can do it too 

```
CsvParser.mapWith(CsvMapperFactory.newInstance().addAlias("from", "to").newMapper(clazz)).iterator("ddd");
```
