### ISSUE TITLE
Nested members can't be extracted in Java 11

### ISSUE THREAD

**Issue by anuraaga** [arnaudroger/SimpleFlatMapper#556]
I updated a codebase to Java 11 but mapping doesn't work with this exception

```
	at org.simpleflatmapper.ow2asm.ClassVisitor.visitNestMemberExperimental(ClassVisitor.java:248)
	at org.simpleflatmapper.ow2asm.ClassReader.accept(ClassReader.java:651)
	at org.simpleflatmapper.ow2asm.ClassReader.accept(ClassReader.java:391)
	at org.simpleflatmapper.reflect.asm.AsmInstantiatorDefinitionFactory.extractDefinitions(AsmInstantiatorDefinitionFactory.java:41)
	at org.simpleflatmapper.reflect.ReflectionService.extractInstantiator(ReflectionService.java:263)
	at org.simpleflatmapper.reflect.meta.ObjectClassMeta.<init>(ObjectClassMeta.java:42)
	at org.simpleflatmapper.reflect.ReflectionService.newClassMeta(ReflectionService.java:211)
	at org.simpleflatmapper.reflect.ReflectionService.getClassMeta(ReflectionService.java:177)
	at org.simpleflatmapper.jooq.SfmRecordMapperProvider.provide(SfmRecordMapperProvider.java:47)
	at org.jooq.impl.ResultImpl.intoMap(ResultImpl.java:586)
	at org.jooq.impl.AbstractResultQuery.fetchMap(AbstractResultQuery.java:1048)
	at org.jooq.impl.SelectImpl.fetchMap(SelectImpl.java:3361)
```

I think it's because the ASM version is fixed here, while on Java 11 ASM7_EXPERIMENTAL needs to be used.

https://github.com/arnaudroger/SimpleFlatMapper/blob/master/sfm-reflect/src/main/java/org/simpleflatmapper/reflect/asm/AsmInstantiatorDefinitionFactory.java#L41

Would it make sense to add a parameter to `ReflectionService` to allow setting the ASM API level?

**Comment by arnaudroger** [comment]
Thanks will have a look

**Comment by arnaudroger** [comment]
What was the actual exception thrown seems to be missing from the stcktrace

**Comment by anuraaga** [comment]
Ah shoot - it's `UnsupportedOperationException`. Will try to recreate the stack trace for completeness

**Comment by arnaudroger** [comment]
never mind could not see it on my phone but it's there

**Comment by arnaudroger** [comment]
Oh I see nested member humm :)

**Comment by anuraaga** [comment]
FWIW, I tried forking the two classes and using `System.property("java.version").equals("11")` to switch to ASMV7_EXPERIMENTAL and it works fine. Not sure if it's the best fix (maybe just adding `UnsupportedOperationException` to the catch clauses is better.

**Comment by arnaudroger** [comment]
yes that should do it will check it I can also upgrade to 6.2 with the Opcodes.ASMV7_EXPERIMENTAL when java 8

**Comment by arnaudroger** [comment]
just pushed a quick change on master, could you check if that fix the problem? 
should make use ASM7 EXP for all java8 and upwards build.

**Comment by arnaudroger** [comment]
just pushed 5.0.2 to maven central - should be available in 30 minutes, that hopefully will fix the issue, @anuraaga could confirm when you have time?
