### ISSUE TITLE
filter property on wether we can get a getter or not

### ISSUE THREAD

**Issue by arnaudroger** [arnaudroger/SimpleFlatMapper#572]
should we had a filter on I can actually get a getter for that?

**Comment by amitgol** [comment]
Is this no longer planned? Not sure if this is same issue, but what I see is that when mapping one-to-many result set, there is an issue if a property does not exist on a child entity, and there is no way to ignore it. I tried swallowing the exception using a custom  `MapperBuilderErrorHandler` but this causes the list of child entities to return with only one element.

**Comment by arnaudroger** [comment]
Could you send the mapping error it sends? Also you can ask the mapper to ignore a column 
addColumnProperty( columnname, new IgnoreProperty())
On the mapper factory

**Comment by amitgol** [comment]
org.simpleflatmapper.map.MapperBuildingException: Could not find getter for ColumnKey [columnName=order_items_trace_context, columnIndex=17, sqlType=1111] type class com.behalf.persistence_test.domain.OrderItem path [1]. See https://github.com/arnaudroger/SimpleFlatMapper/wiki/Errors_CSFM_GETTER_NOT_FOUND
	at org.simpleflatmapper.map.IgnoreMapperBuilderErrorHandler.accessorNotFound(IgnoreMapperBuilderErrorHandler.java:15)
	at org.simpleflatmapper.map.fieldmapper.ConstantSourceFieldMapperFactoryImpl.newFieldMapper(ConstantSourceFieldMapperFactoryImpl.java:202)
	at org.simpleflatmapper.map.mapper.DefaultConstantSourceMapperBuilder.newFieldMapper(DefaultConstantSourceMapperBuilder.java:920)
	at org.simpleflatmapper.map.mapper.DefaultConstantSourceMapperBuilder$PropertyFieldMeta.targetFieldMapper(DefaultConstantSourceMapperBuilder.java:757)
	at org.simpleflatmapper.map.mapper.DefaultConstantSourceMapperBuilder.targetFieldMappers(DefaultConstantSourceMapperBuilder.java:649)
	at org.simpleflatmapper.map.mapper.DefaultConstantSourceMapperBuilder.sourceFieldMapper(DefaultConstantSourceMapperBuilder.java:196)
	at org.simpleflatmapper.map.mapper.DefaultConstantSourceMapperBuilder.subPropertyMapper(DefaultConstantSourceMapperBuilder.java:908)
	at org.simpleflatmapper.map.mapper.DefaultConstantSourceMapperBuilder.access$2400(DefaultConstantSourceMapperBuilder.java:69)
	at org.simpleflatmapper.map.mapper.DefaultConstantSourceMapperBuilder$SubPropertyParam.getsSourceMapper(DefaultConstantSourceMapperBuilder.java:1274)
	at org.simpleflatmapper.map.mapper.DefaultConstantSourceMapperBuilder$SubPropertyParam.getterAndfieldMapper(DefaultConstantSourceMapperBuilder.java:1230)
	at org.simpleflatmapper.map.mapper.DefaultConstantSourceMapperBuilder.toConstructorInjections(DefaultConstantSourceMapperBuilder.java:519)
	at org.simpleflatmapper.map.mapper.DefaultConstantSourceMapperBuilder.sourceFieldMapper(DefaultConstantSourceMapperBuilder.java:194)
	at org.simpleflatmapper.map.mapper.DefaultConstantSourceMapperBuilder.mapper(DefaultConstantSourceMapperBuilder.java:133)


This getter really doesn't exist since the field exists on the record but not on the model.

I haven't checked your suggestion for `addColumnProperty` but if I need to namely exclude it, it's easier to exclude it from the select statement (since I need to select field by field anyway and give them aliases)

**Comment by arnaudroger** [comment]
so the getter here is a getter from the result set to the pojo, it mapped order_items_trace_context to an OrderItem in the array with index 1. prob a bad decision that's definitly what the getter filter is supposed to do.
And II guess that will interfer with the mapper builder if the exception is caught and break the join.
definitly something I'll need to adress there....

**Comment by arnaudroger** [comment]
just been pushed with 6.1.0 @amitgol I don't know if that will fix your underlying issue, but should be available in maven central in 20-30 mn

**Comment by arnaudroger** [comment]
Nop unexpected though no jooq test broke. Will try and reproduce might need more details about type of id field in dB and in the pojo. I supposed it’s to map from record to pojo

**Comment by arnaudroger** [comment]
I might need the full pojo desc and the column from the query.
The only thing that change is that it fails earlier on column with no way to get value from record
