### ISSUE TITLE
Howto integrate with immutables.org?

### ISSUE THREAD

**Issue by davidkarlsen** [arnaudroger/SimpleFlatMapper#574]
Do you have a starter/docs on howto integrate with immutable.org beans?

**Comment by arnaudroger** [comment]
from what I can recall it should just work like that, sfm should recognize the builder and use it.
have you encountered any issue?

**Comment by arnaudroger** [comment]
there is a sample projects there https://github.com/arnaudroger/SimpleFlatMapper/tree/master/sfm-test-immutables for testing

**Comment by davidkarlsen** [comment]
Great - it works very well ootb for a row -> immutable bean - but when I have a join between two tables, I basically need a two-fold mapping, like this:
```
        ImmutableMetaData metaData = entry.getKey().into(ImmutableMetaData.class);
        ImmutableLobData ild = ImmutableLobData.builder(); // will fail here due to build() being called
        return entry.getValue().get(0).into(ild).withMetaData(metaData).
```

however - this fails because the build() is called by the library (and not all required attributes are set).

Would it be possible to adapt it to use the builder - so that the builder could be returned which I could add more attributes to, and then I call build() myself?

**Comment by arnaudroger** [comment]
so you can get the library to instantiate the Builder instead of the value. it requires a bit more work because it won't figure out by itself how to instantiate the builder but it goes as follow

```java 
        final ClassMeta<ImmutableFoobarValue.Builder> meta =
                mapperFactory
                        .getClassMetaWithExtraInstantiator(
                                ImmutableFoobarValue.Builder.class,
                                ImmutableFoobarValue.class.getMethod("builder"));
        JdbcMapper<ImmutableFoobarValue.Builder> mapper = JdbcMapperFactory.newInstance().newMapper(meta);

```
the idea to instantiate the meta with the specified instantiator.
I'm not really sure if that solves your problem there?

**Comment by paulolieuthier** [comment]
It would be really nice to have automatic integration so to not need to define the static builder method or the extra instantiatior.

**Comment by arnaudroger** [comment]
would need to look, would need to scan the enclosing class for builder method might be possible

**Comment by arnaudroger** [comment]
just pushed 3.2.0 out it should just work now with 
```java 
JdbcMapper<ImmutableFoobarValue.Builder> mapper = JdbcMapperFactory.newInstance().newMapper(ImmutableFoobarValue.Builder.class);
```

**Comment by paulolieuthier** [comment]
This is very nice, thanks for the quick response. Unfortunately, now I see I misread the issue. What I would like to do is to use the interface and have sfm use the immutable implementation automatically:

```java
@Value.Immutable
public interface ReallyUsefulInformation {
    String info();
}

public interface ReallyUsefulInformationDao {
    @SqlQuery("...")
    ReallyUsefulInformation getReallyUsefulInformation();
}
```
Maybe I could help you build `sfm-immutables` to actually detect `@Value.Immutable` and use the generated immutable class?

This is the error I get:
```
org.simpleflatmapper.map.MapperBuildingException: Could not find eligible property for 'info' on  interface ...ReallyUsefulInformation not found  See https://github.com/arnaudroger/SimpleFlatMapper/wiki/Errors_PROPERTY_NOT_FOUND
	at org.simpleflatmapper.map.error.RethrowMapperBuilderErrorHandler.propertyNotFound(RethrowMapperBuilderErrorHandler.java:26)
	at org.simpleflatmapper.map.mapper.PropertyMappingsBuilder._addProperty(PropertyMappingsBuilder.java:105)
	at org.simpleflatmapper.map.mapper.PropertyMappingsBuilder.addProperty(PropertyMappingsBuilder.java:69)
	at org.simpleflatmapper.map.mapper.DefaultConstantSourceMapperBuilder.addMapping(DefaultConstantSourceMapperBuilder.java:159)
	at org.simpleflatmapper.map.mapper.SetRowMapperBuilderImpl.addMapping(SetRowMapperBuilderImpl.java:206)
	at org.simpleflatmapper.map.mapper.MapperBuilder.addMapping(MapperBuilder.java:142)
	at org.simpleflatmapper.map.mapper.MapperBuilder.addMapping(MapperBuilder.java:152)
	at org.simpleflatmapper.jdbc.JdbcMapperFactory$SetRowMapperFactory.newInstance(JdbcMapperFactory.java:344)
	at org.simpleflatmapper.jdbc.JdbcMapperFactory$SetRowMapperFactory.newInstance(JdbcMapperFactory.java:332)
	at org.simpleflatmapper.map.mapper.DynamicSetRowMapper.getMapper(DynamicSetRowMapper.java:104)
	at org.simpleflatmapper.jdbc.JdbcMapperFactory$DynamicJdbcSetRowMapper.getMapper(JdbcMapperFactory.java:299)
	at org.simpleflatmapper.jdbi3.DynamicRowMapper.specialize(DynamicRowMapper.java:25)
	at org.jdbi.v3.core.result.ResultSetResultIterator.<init>(ResultSetResultIterator.java:38)
	at org.jdbi.v3.core.result.ResultIterable.lambda$of$0(ResultIterable.java:53)
	at org.jdbi.v3.core.result.ResultIterable.findFirst(ResultIterable.java:116)
	at org.jdbi.v3.sqlobject.statement.internal.ResultReturner$CollectedResultReturner.mappedResult(ResultReturner.java:276)
	at org.jdbi.v3.sqlobject.statement.internal.SqlQueryHandler.lambda$configureReturner$0(SqlQueryHandler.java:54)
	at org.jdbi.v3.sqlobject.statement.internal.CustomizingStatementHandler.invoke(CustomizingStatementHandler.java:155)
	at org.jdbi.v3.sqlobject.statement.internal.SqlQueryHandler.invoke(SqlQueryHandler.java:26)
	at org.jdbi.v3.sqlobject.SqlObjectFactory.lambda$null$13(SqlObjectFactory.java:158)
	at org.jdbi.v3.core.internal.JdbiThreadLocals.invokeInContext(JdbiThreadLocals.java:27)
	at org.jdbi.v3.core.LazyHandleSupplier.lambda$invokeInContext$1(LazyHandleSupplier.java:72)
	at org.jdbi.v3.core.internal.JdbiThreadLocals.invokeInContext(JdbiThreadLocals.java:27)
	at org.jdbi.v3.core.LazyHandleSupplier.invokeInContext(LazyHandleSupplier.java:71)
	at org.jdbi.v3.sqlobject.SqlObjectFactory.lambda$createInvocationHandler$14(SqlObjectFactory.java:157)
	at org.jdbi.v3.core.OnDemandExtensions.invoke(OnDemandExtensions.java:76)
	at org.jdbi.v3.core.OnDemandExtensions.lambda$null$0(OnDemandExtensions.java:63)
	at org.jdbi.v3.core.internal.JdbiThreadLocals.invokeInContext(JdbiThreadLocals.java:27)
	at org.jdbi.v3.core.OnDemandExtensions.lambda$null$1(OnDemandExtensions.java:62)
	at org.jdbi.v3.core.Jdbi.withExtension(Jdbi.java:439)
	at org.jdbi.v3.core.OnDemandExtensions.lambda$create$2(OnDemandExtensions.java:61)
	at com.sun.proxy.$Proxy42.getReallyUsefulInformation(Unknown Source)
	at ...ReallyUsefulInformationFacade.getReallyUsefulInformation(ReallyUsefulInformationFacade.java:18)
...
```

**Comment by arnaudroger** [comment]
that might be possible, it prob would be a different module if it needs dep to immutable library
create ticket https://github.com/arnaudroger/SimpleFlatMapper/issues/609
