### ISSUE TITLE
Issue using .discriminator() and .addCustomGetter()

### ISSUE THREAD

**Issue by n1b0r** [arnaudroger/SimpleFlatMapper#614]
Hello,

I'm getting troubles while trying to use a mapper declared as : 

```
JdbcMapper mapper = JdbcMapperFactory
	.newInstance()
	.discriminator(A.class,
			"a_type",
		        ResultSet::getString,
			builder -> builder.when("A1", A1.class)
							  .when("A2", A2.class)
							  .when(v -> true, A.class)
	)
	.addCustomGetter(
			"a_json",
			rs -> new ObjectMapper().readValue(
					((PGobject)rs.getObject("a_json")).getValue(),
					new TypeReference<Map<String, String>>()
			{
			}))
	.newMapper(B.class);
```

Here is the error :

```
Exception in thread "main" java.lang.UnsupportedOperationException
	at org.simpleflatmapper.map.impl.DiscriminatorPropertyFinder$DiscriminatorPropertyMeta.getPropertyType(DiscriminatorPropertyFinder.java:190)
	at org.simpleflatmapper.reflect.meta.SubPropertyMeta.getPropertyType(SubPropertyMeta.java:61)
	at org.simpleflatmapper.map.mapper.PropertyMappingsBuilder.addProperty(PropertyMappingsBuilder.java:157)
	at org.simpleflatmapper.map.mapper.PropertyMappingsBuilder._addProperty(PropertyMappingsBuilder.java:107)
	at org.simpleflatmapper.map.mapper.PropertyMappingsBuilder.addProperty(PropertyMappingsBuilder.java:75)
	at org.simpleflatmapper.map.mapper.DefaultConstantSourceMapperBuilder.addMapping(DefaultConstantSourceMapperBuilder.java:117)
	at org.simpleflatmapper.map.mapper.SetRowMapperBuilderImpl.addMapping(SetRowMapperBuilderImpl.java:202)
	at org.simpleflatmapper.map.mapper.MapperBuilder.addMapping(MapperBuilder.java:142)
	at org.simpleflatmapper.map.mapper.MapperBuilder.addMapping(MapperBuilder.java:152)
	at org.simpleflatmapper.jdbc.JdbcMapperFactory$SetRowMapperFactory.newInstance(JdbcMapperFactory.java:342)
	at org.simpleflatmapper.jdbc.JdbcMapperFactory$SetRowMapperFactory.newInstance(JdbcMapperFactory.java:330)
	at org.simpleflatmapper.map.mapper.DynamicSetRowMapper.getMapper(DynamicSetRowMapper.java:104)
	at org.simpleflatmapper.map.mapper.DynamicSetRowMapper.getMapperFromSet(DynamicSetRowMapper.java:94)
	at org.simpleflatmapper.map.mapper.DynamicSetRowMapper.stream(DynamicSetRowMapper.java:70)
	at org.simpleflatmapper.jdbc.JdbcMapperFactory$DynamicJdbcSetRowMapper.stream(JdbcMapperFactory.java:283)
```

Here is my test case to reproduce :

```
public class A
{
	public HashMap<String, String> json;
	public String type;
}

public class A1 extends A
{

}
public class A2 extends A
{

}

public class B
{
	public Integer id;
	public A a;
}

public static void main(String[] args) throws SQLException
{
	JdbcMapper mapper = JdbcMapperFactory
			.newInstance()
			.discriminator(A.class,
					"a_type",
					ResultSet::getString,
					builder -> builder.when("A1", A1.class)
									  .when("A2", A2.class)
									  .when(v -> true, A.class)
			)
			.addCustomGetter(
					"a_json",
					rs -> new ObjectMapper().readValue(
							((PGobject)rs.getObject("a_json")).getValue(),
							new TypeReference<Map<String, String>>()
					{
					}))
			.newMapper(B.class);

	DataSource datasource = new DataSource();
	datasource.setUrl("jdbc:postgresql://<host>:5432/<table>?user=<user>");

	try (Connection c = datasource.getConnection();
		 Statement s = c.createStatement();
		 ResultSet rs = s.executeQuery("select 1 as id, '{\"a\": \"a\"}'::json as a_json, 'A1' as a_type"))
	{
		mapper
				.stream(rs)
				.forEach(System.out::println);
	}
}

```

If you comment the .discriminator() the logic is working as expected, but if you keep the .discriminator(), error is raised.

Am I doing something wrong ?

**Comment by arnaudroger** [comment]
Will have a look thanks for the bug report

**Comment by arnaudroger** [comment]
so thanks for reproducer, it's a bug when using custom getter, might be able to ship a fix later tonight.

**Comment by arnaudroger** [comment]
I pushed 6.4.1 to maven central with a fix for it, it seems to be taking longer than usual to become available but hopefully will be there soon enough

**Comment by n1b0r** [comment]
Thanks for your time, the fix is working.

The 6.4.1 has not yet been released on maven central, but installing from sources allowed me to test it.

One small question about your commit. Why don't you assert something into your test ? How are you sure that the returned value is what you expected ?

**Comment by arnaudroger** [comment]
raised a ticket with sonatype, might be a general issue as somebody else had the the issue.

on the test, 
 the mapping is tested in many other places, 
was mainky checking it was not throwing an exception there.
not ideal, but good enough for me

**Comment by arnaudroger** [comment]
6.4.1 is in maven central

**Comment by n1b0r** [comment]
What do you call maven central ?

I cannot see de 6.4.1 release for sfm-jdbc.

https://mvnrepository.com/artifact/org.simpleflatmapper/sfm-jdbc

**Comment by arnaudroger** [comment]
https://search.maven.org/
