### ISSUE TITLE
Cannot convert oracle.sql.TIMESTAMPTZ after migrate to v6

### ISSUE THREAD

**Issue by lpborges** [arnaudroger/SimpleFlatMapper#616]
After migrate from v5 to v6 my application got a error when convert a Oracle Timestamp column to `ZonedDateTime` field using a `ResultSetExtractor`.
This problem don't occurs with `org.simpleflatmapper:sfm-springjdbc:5.0.1`, but after migrate to v6 the follow exception happens:
```
Caused by: java.lang.IllegalArgumentException: Cannot convert oracle.sql.TIMESTAMPTZ@4229b154 to ZonedDateTime
	at org.simpleflatmapper.converter.impl.time.ObjectToJavaZonedDateTimeConverter.convert(ObjectToJavaZonedDateTimeConverter.java:44)
	at org.simpleflatmapper.converter.impl.time.ObjectToJavaZonedDateTimeConverter.convert(ObjectToJavaZonedDateTimeConverter.java:11)
	at org.simpleflatmapper.map.fieldmapper.FieldMapperGetterWithConverter.get(FieldMapperGetterWithConverter.java:22)
	at org.simpleflatmapper.map.generated.com.company.eva.operation.model.entity.AsmMapperFromResultSetToMissionSummaryRouteInj7_Ib.mapFields(Unknown Source)
	at org.simpleflatmapper.map.generated.com.company.eva.operation.model.entity.AsmMapperFromResultSetToMissionSummaryRouteInj7_Ib.mapFields(Unknown Source)
	at org.simpleflatmapper.map.mapper.AbstractMapper.map(AbstractMapper.java:23)
	at org.simpleflatmapper.map.fieldmapper.MapperFieldMapper.mapTo(MapperFieldMapper.java:40)
	at org.simpleflatmapper.map.generated.com.company.eva.operation.model.entity.AsmMapperFromResultSetToMissionSummaryOrderInj4_Ic.mapFields(Unknown Source)
	at org.simpleflatmapper.map.generated.com.company.eva.operation.model.entity.AsmMapperFromResultSetToMissionSummaryOrderInj4_Ic.mapFields(Unknown Source)
	at org.simpleflatmapper.map.mapper.AbstractMapper.map(AbstractMapper.java:23)
	at org.simpleflatmapper.map.fieldmapper.MapperFieldMapper.mapTo(MapperFieldMapper.java:40)
	at org.simpleflatmapper.map.generated.java.util.AsmMapperFromResultSetToListInj1_Id.mapFields(Unknown Source)
	at org.simpleflatmapper.map.generated.java.util.AsmMapperFromResultSetToListInj1_Id.mapFields(Unknown Source)
	at org.simpleflatmapper.map.mapper.AbstractMapper.map(AbstractMapper.java:23)
	at org.simpleflatmapper.map.fieldmapper.MapperFieldMapper.mapTo(MapperFieldMapper.java:40)

```

**Comment by arnaudroger** [comment]
will have a look thanks for the issue

**Comment by arnaudroger** [comment]
alright so oracle is a bit weird for those thing but should be able to add something to handle that.

**Comment by arnaudroger** [comment]
which version of the oracle driver are you using?

**Comment by lpborges** [comment]
> which version of the oracle driver are you using?

This project is using ojdbc7:12.1.0.1.0

**Comment by arnaudroger** [comment]
I just pushed a change in master to deal with that, but I don't have an oracle db, could you check it out locally ?

**Comment by lpborges** [comment]
Just testes and got another error now:

```
Caused by: java.lang.reflect.InvocationTargetException: null
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.simpleflatmapper.converter.impl.time.ObjectToJavaZonedDateTimeConverter$MethodAccessor.apply(ObjectToJavaZonedDateTimeConverter.java:117)
	at org.simpleflatmapper.converter.impl.time.ObjectToJavaZonedDateTimeConverter$MethodAccessor.apply(ObjectToJavaZonedDateTimeConverter.java:107)
	at org.simpleflatmapper.converter.impl.time.ObjectToJavaZonedDateTimeConverter.getWithCustomAccessor(ObjectToJavaZonedDateTimeConverter.java:82)
	at org.simpleflatmapper.converter.impl.time.ObjectToJavaZonedDateTimeConverter.convert(ObjectToJavaZonedDateTimeConverter.java:51)
	at org.simpleflatmapper.converter.impl.time.ObjectToJavaZonedDateTimeConverter.convert(ObjectToJavaZonedDateTimeConverter.java:17)
	at org.simpleflatmapper.map.fieldmapper.FieldMapperGetterWithConverter.get(FieldMapperGetterWithConverter.java:22)
	at org.simpleflatmapper.map.generated.com.company.eva.operation.model.entity.AsmMapperFromResultSetToMissionSummaryRouteInj7_Ib.mapFields(Unknown Source)
	at org.simpleflatmapper.map.generated.com.company.eva.operation.model.entity.AsmMapperFromResultSetToMissionSummaryRouteInj7_Ib.mapFields(Unknown Source)
	at org.simpleflatmapper.map.mapper.AbstractMapper.map(AbstractMapper.java:23)
	at org.simpleflatmapper.map.fieldmapper.MapperFieldMapper.mapTo(MapperFieldMapper.java:40)
	at org.simpleflatmapper.map.generated.com.company.eva.operation.model.entity.AsmMapperFromResultSetToMissionSummaryOrderInj4_Ic.mapFields(Unknown Source)
	at org.simpleflatmapper.map.generated.com.company.eva.operation.model.entity.AsmMapperFromResultSetToMissionSummaryOrderInj4_Ic.mapFields(Unknown Source)
	at org.simpleflatmapper.map.mapper.AbstractMapper.map(AbstractMapper.java:23)
	at org.simpleflatmapper.map.fieldmapper.MapperFieldMapper.mapTo(MapperFieldMapper.java:40)
	at org.simpleflatmapper.map.generated.java.util.AsmMapperFromResultSetToListInj1_Id.mapFields(Unknown Source)
	at org.simpleflatmapper.map.generated.java.util.AsmMapperFromResultSetToListInj1_Id.mapFields(Unknown Source)
	at org.simpleflatmapper.map.mapper.AbstractMapper.map(AbstractMapper.java:23)
	at org.simpleflatmapper.map.fieldmapper.MapperFieldMapper.mapTo(MapperFieldMapper.java:40)
	at org.simpleflatmapper.map.generated.com.company.eva.operation.model.entity.AsmMapperFromResultSetToMissionSummaryInj9_Ie.mapFields(Unknown Source)
	at org.simpleflatmapper.map.generated.com.company.eva.operation.model.entity.AsmMapperFromResultSetToMissionSummaryInj9_Ie.mapFields(Unknown Source)
	at org.simpleflatmapper.map.mapper.AbstractMapper.map(AbstractMapper.java:23)
	at org.simpleflatmapper.map.mapper.ContextualSourceFieldMapperImpl.map(ContextualSourceFieldMapperImpl.java:36)
	at org.simpleflatmapper.map.mapper.JoinMapperEnumerable.next(JoinMapperEnumerable.java:37)
	at org.simpleflatmapper.map.mapper.AbstractEnumerableMapper.forEach(AbstractEnumerableMapper.java:33)
	at org.simpleflatmapper.jdbc.JdbcMapperBuilder$JdbcMapperImpl.forEach(JdbcMapperBuilder.java:230)
	at org.simpleflatmapper.jdbc.JdbcMapperBuilder$JdbcMapperImpl.forEach(JdbcMapperBuilder.java:209)
	at org.simpleflatmapper.map.mapper.DynamicSetRowMapper.forEach(DynamicSetRowMapper.java:83)
	at org.simpleflatmapper.jdbc.JdbcMapperFactory$DynamicJdbcSetRowMapper.forEach(JdbcMapperFactory.java:285)
	at org.simpleflatmapper.jdbc.spring.ResultSetExtractorImpl.extractData(ResultSetExtractorImpl.java:60)
	at org.simpleflatmapper.jdbc.spring.ResultSetExtractorImpl.extractData(ResultSetExtractorImpl.java:50)
	at org.springframework.jdbc.core.JdbcTemplate$1.doInPreparedStatement(JdbcTemplate.java:703)
	at org.springframework.jdbc.core.JdbcTemplate.execute(JdbcTemplate.java:639)
	at org.springframework.jdbc.core.JdbcTemplate.query(JdbcTemplate.java:690)
	at org.springframework.jdbc.core.JdbcTemplate.query(JdbcTemplate.java:717)
	at org.springframework.jdbc.core.namedparam.NamedParameterJdbcTemplate.query(NamedParameterJdbcTemplate.java:154)
	at com.company.eva.operation.model.repository.jdbc.MissionSummaryRepository.findBy(MissionSummaryRepository.java:79)
	at com.company.eva.operation.model.repository.jdbc.MissionSummaryRepository$$FastClassBySpringCGLIB$$f6b6bb0b.invoke(<generated>)
	at org.springframework.cglib.proxy.MethodProxy.invoke(MethodProxy.java:204)
	at org.springframework.aop.framework.CglibAopProxy$CglibMethodInvocation.invokeJoinpoint(CglibAopProxy.java:736)
	at org.springframework.aop.framework.ReflectiveMethodInvocation.proceed(ReflectiveMethodInvocation.java:157)
	at org.springframework.dao.support.PersistenceExceptionTranslationInterceptor.invoke(PersistenceExceptionTranslationInterceptor.java:136)
	at org.springframework.aop.framework.ReflectiveMethodInvocation.proceed(ReflectiveMethodInvocation.java:179)
	at org.springframework.aop.framework.CglibAopProxy$DynamicAdvisedInterceptor.intercept(CglibAopProxy.java:671)
	... 118 common frames omitted
Caused by: java.sql.SQLException: Conversion to Timestamp failed
	at oracle.sql.Datum.timestampValue(Datum.java:334)
```

**Comment by lpborges** [comment]
I don't got the time to check the changes to find out why on v5 (and previous) its works

**Comment by arnaudroger** [comment]
it worked because it defaulted to call getTimestamp, I think with jdbc4.2 if the driver is compliant it should return OffsetDateTime, but oracle driver returns its own weird type. I'll just push that then you see later if that fixes it.

**Comment by arnaudroger** [comment]
ok I think I found the root explanation and pushed a fix for it, would you mind trying again when you have time. long story short we started using the columnClass from the meta data when available for the column type and that made it using the TIMESTAMPTZ. know it will ignore it if it does not match the target type and is not a java core class. that should fix the issue

**Comment by arnaudroger** [comment]
6.4.2 release to maven central hopefully it fixes the issue

**Comment by lpborges** [comment]
> 6.4.2 release to maven central hopefully it fixes the issue

Tested with 6.4.2, works fine now.
Thanks for the fast fix.

**Comment by arnaudroger** [comment]
Thanks!
