### ISSUE TITLE
ConnectedCrud  ignorePropertyNotFound error

### ISSUE THREAD

**Issue by cn-src** [arnaudroger/SimpleFlatMapper#749]
If use the ignorePropertyNotFound() method, an exception will occur.

```java
 final ConnectedCrud<Demo, Long> crud = JdbcMapperFactory.newInstance()
            .ignorePropertyNotFound()
            .crud(Demo.class, Long.class)
            .table(pg, "demo");
```

```
java.lang.IllegalArgumentException: No constructor available for class java.lang.Long

	at org.simpleflatmapper.reflect.InstantiatorFactory.getBiInstantiator(InstantiatorFactory.java:51)
	at org.simpleflatmapper.map.mapper.MapperBiInstantiatorFactory.getBiInstantiator(MapperBiInstantiatorFactory.java:57)
	at org.simpleflatmapper.map.mapper.MapperBiInstantiatorFactory.getBiInstantiator(MapperBiInstantiatorFactory.java:33)
	at org.simpleflatmapper.map.mapper.DefaultConstantSourceMapperBuilder.getConstructorFieldMappersAndInstantiator(DefaultConstantSourceMapperBuilder.java:594)
	at org.simpleflatmapper.map.mapper.DefaultConstantSourceMapperBuilder.sourceFieldMapper(DefaultConstantSourceMapperBuilder.java:228)
	at org.simpleflatmapper.map.mapper.DefaultConstantSourceMapperBuilder.mapper(DefaultConstantSourceMapperBuilder.java:166)
	at org.simpleflatmapper.map.mapper.SetRowMapperBuilderImpl.sourceFieldMapper(SetRowMapperBuilderImpl.java:196)
	at org.simpleflatmapper.map.mapper.SetRowMapperBuilderImpl.mapper(SetRowMapperBuilderImpl.java:109)
	at org.simpleflatmapper.map.mapper.MapperBuilder.mapper(MapperBuilder.java:42)
	at org.simpleflatmapper.jdbc.impl.CrudFactory.buildKeyMapper(CrudFactory.java:108)
	at org.simpleflatmapper.jdbc.impl.CrudFactory.createCrud(CrudFactory.java:42)
	at org.simpleflatmapper.jdbc.impl.CrudFactory.newInstance(CrudFactory.java:26)
	at org.simpleflatmapper.jdbc.CrudDSL.table(CrudDSL.java:57)
	at org.simpleflatmapper.jdbc.CrudDSL.table(CrudDSL.java:70)
```

**Comment by arnaudroger** [comment]
I'll have a  look it does  not seem to be link the could you give  me the description  of the table  and the Demo class?
